#! /usr/bin/env bash
echo = "creating bucket..."

#this checks if at least one argument is provided
if [ -z "$1" ]; then
    echo "No bucket name provided."
    exit 1
fi

BUCKET_NAME=$1

aws s3api create-bucket \
    --bucket $BUCKET_NAME \
    --region eu-west-2 \
    --create-bucket-configuration LocationConstraint=eu-west-2 \
    --query Location \
    --output text
